In [1]:
print("hello")

hello


In [2]:
print(2+6)

8


In [3]:
list=[0,1,2]

In [4]:
list*2


[0, 1, 2, 0, 1, 2]

In [5]:
arr=np.array([0,1,2])

NameError: name 'np' is not defined

In [6]:
arr*2

NameError: name 'arr' is not defined

In [7]:
arr= np.array([0,1,2])
arr*2

NameError: name 'np' is not defined

In [9]:
my_list=[-1,0,1]
my_array= np.array(my_list)
my_array

NameError: name 'np' is not defined

In [10]:
import numpy as np


In [11]:
my_list=[-1,0,1]
my_array= np.array(my_list)
my_array

array([-1,  0,  1])

In [12]:
type(my_array)

numpy.ndarray

In [13]:
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [15]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [23]:
np.full(5, 10)


array([10, 10, 10, 10, 10])

In [24]:
np.arange(52, 100, 2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

In [25]:
 np.eye(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [26]:
matrix = np.array([
    [0.99598801, 0.07546767, 0.17484793, 0.25229956, 0.4693597],
    [0.5591561, 0.5007227, 0.93630239, 0.48747691, 0.78658124],
    [0.98923838, 0.04124599, 0.71326198, 0.51252888, 0.36130539],
    [0.11558779, 0.52914213, 0.31134907, 0.8047612, 0.25759207],
    [0.87331331, 0.77104413, 0.960445, 0.1732589, 0.83339285],
    [0.99839604, 0.78268012, 0.66487603, 0.14509928, 0.05670129],
    [0.15932364, 0.848172, 0.51343887, 0.06309231, 0.29250649]
])
matrix

array([[0.99598801, 0.07546767, 0.17484793, 0.25229956, 0.4693597 ],
       [0.5591561 , 0.5007227 , 0.93630239, 0.48747691, 0.78658124],
       [0.98923838, 0.04124599, 0.71326198, 0.51252888, 0.36130539],
       [0.11558779, 0.52914213, 0.31134907, 0.8047612 , 0.25759207],
       [0.87331331, 0.77104413, 0.960445  , 0.1732589 , 0.83339285],
       [0.99839604, 0.78268012, 0.66487603, 0.14509928, 0.05670129],
       [0.15932364, 0.848172  , 0.51343887, 0.06309231, 0.29250649]])

In [28]:
array_1d = np.linspace(0, 24, 25, dtype=int)
matrix = array_1d.reshape(5, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [33]:
matrix = np.array([
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24]
])
vector = matrix.ravel()

vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
result_array = np.arange(0, 1.11111111, 0.11111111)
increment = result_array[1] - result_array[0]
result_array, increment

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555555, 0.66666666, 0.77777777, 0.88888888, 0.99999999,
        1.1111111 ]),
 0.11111111)

In [35]:
array_1d = np.arange(25)
matrix = array_1d.reshape(5, 5)
matrix


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
array_1d = np.arange(0.1, 2.6, 0.1)
matrix = array_1d.reshape(5, 5)
matrix

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

In [37]:
random_integer = np.random.randint(0, 10)
random_integer

8

In [38]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

In [39]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 2, 100, retstep = True)

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [41]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1,2, retstep = True)

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
        1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
        1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
        1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
        1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
        1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
        1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
        1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
        1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
        1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]),
 0.02040816326530612)